### ISSUE TITLE
Add a license (AGPL)

### ISSUE THREAD

**Issue by bbambozzi** [nsatragno/aoc2022#1]
I've noticed this project has no license. I suggest it was added a license that guaranteed the freedom to copy, distribute and modify the contents of this repo? I suggest the very excellent [AGPL](https://www.gnu.org/licenses/agpl-3.0.en.html) sponsored by the [Free Software Foundation](https://www.fsf.org/)

**Comment by nsatragno** [comment]
Let's do MIT, so I can copy-paste my code for my secret, proprietary projects at $company.
